# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "契克BLOG"
brief-intro: "你是那抹明亮俏皮的柠檬黄吗？"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cococomeon.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username: #gaohaoyang126
facebook_username: #gaohaoyang.water
github_username:  cococomeon
email: tschick1031@gmail.com
weibo_username: 契克5654
zhihu_username: 
linkedIn_username:
dribbble_username:

description_footer: 尝试记录生活学习工作的点滴

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
# duoshuo_shortname: xyao #hygblog
# disqus_shortname: #gaohaoyang
# using Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: e4c1308042e6f9757e3e                            #生成的clientID
  clientSecret: f1f764e58f1574fa91aa0a92ba5c09d51803c4f9    #生成的clientSecret
  repo: cococomeon.github.io    #仓库名称
  owner: cococomeon    #github用户名
  admin: cococomeon
  distractionFreeMode: true #是否启用类似FB的阴影遮罩

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
#baidu_tongji_id: 2bb59fa5bdcce1298213fbf552392691
google_analytics_id: 207965150 # google 分析追踪id
ga_domain: auto

friends: [
    {
        title: "Linkedin - Dennis Li",
        href: ""
    }
]

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
plugins: [jekyll-paginate]
paginate: 6
port: 4001
